import { createRequire } from 'node:module';
import { writeFile, mkdir } from 'node:fs/promises';
import assert from 'node:assert/strict';
const require=createRequire(import.meta.url);
const {chromium}=require(process.env.PLAYWRIGHT_MODULE ?? 'playwright');
const origin=process.env.EDGE_TEST_ORIGIN ?? 'https://127.0.0.1:8162';
const output=process.env.EDGE_EVIDENCE_DIR ?? './test-artifacts';
await mkdir(output,{recursive:true});
const browser=await chromium.launch({headless:true,executablePath:process.env.CHROMIUM_PATH,args:['--autoplay-policy=no-user-gesture-required']});
try {
 const context=await browser.newContext({ignoreHTTPSErrors:true,viewport:{width:1600,height:1100}});
 const page=await context.newPage(),errors=[];page.on('pageerror',error=>{errors.push(error.message);console.error('PAGEERROR',error.message);});
 for(const path of ['/api/bootstrap','/api/events','/media/crowne.mp4']) assert.equal((await context.request.get(origin+'/edge'+path)).status(),401);
 await page.goto(origin+'/edge');
 await page.getByRole('link',{name:'Entrar con Zitadel'}).click().catch(async error=>{await page.screenshot({path:output+'/edge-zones-failure.png'});console.error(await page.locator('body').innerText());throw error;});
 await page.waitForURL(origin+'/edge');
 await page.waitForFunction(()=>document.querySelectorAll('video[data-edge-video]').length===11);
 await page.waitForFunction(()=>[...document.querySelectorAll('video[data-edge-video]')].every(v=>v.readyState>=3&&!v.paused&&v.currentTime>2),null,{timeout:60000});
 const read=()=>page.locator('video[data-edge-video]').evaluateAll(list=>list.map(v=>({id:v.dataset.edgeVideo,time:v.currentTime,ready:v.readyState,paused:v.paused,path:new URL(v.currentSrc).pathname})));
 const initial=await read();assert(Math.max(...initial.map(v=>v.time))-Math.min(...initial.map(v=>v.time))<.4);
 assert(initial.every(v=>v.path===`/edge/media/${v.id}.mp4`));
 assert.equal(await page.getByRole('button',{name:/en el mapa$/}).count(),11);
 await page.getByText('Corredor 1ª Calle · Bulevar Morazán').waitFor();
 const palette=await page.evaluate(()=>getComputedStyle(document.documentElement).getPropertyValue('--bg').trim());assert.equal(palette,'#081411');
 await page.screenshot({path:output+'/edge-classic-desktop.png',fullPage:true});
 await page.getByRole('button',{name:'Pausar',exact:true}).click();
 await page.waitForFunction(()=>[...document.querySelectorAll('video[data-edge-video]')].every(v=>v.paused));
 const frozen=(await read()).map(v=>v.time);await page.waitForTimeout(600);assert.deepEqual((await read()).map(v=>v.time),frozen);
 await page.getByRole('button',{name:'00:45',exact:true}).click();
 await page.waitForFunction(()=>[...document.querySelectorAll('video[data-edge-video]')].every(v=>Math.abs(v.currentTime-45)<.1),null,{timeout:20000});
 await page.getByRole('button',{name:'Reproducir',exact:true}).click();
 await page.waitForFunction(()=>[...document.querySelectorAll('video[data-edge-video]')].every(v=>v.readyState>=3&&!v.paused&&v.currentTime>46),null,{timeout:20000});
 const sought=await read();assert(Math.max(...sought.map(v=>v.time))-Math.min(...sought.map(v=>v.time))<.4);
 await page.getByRole('button',{name:'Seleccionar Little Caesars 1 en el mapa',exact:true}).click();
 await page.getByRole('button',{name:'Little Caesars 1',exact:true}).waitFor();
 assert.equal(await page.getByRole('button',{name:'Little Caesars 1',exact:true}).getAttribute('aria-pressed'),'true');
 await page.getByRole('button',{name:'Cámara seleccionada',exact:true}).click();
 await page.waitForFunction(()=>document.querySelectorAll('video[data-edge-video]').length===1);
 assert.equal((await read())[0].id,'little1');
 await page.getByRole('button',{name:'Pausar',exact:true}).click();
 await page.waitForFunction(()=>{const c=document.querySelector('[data-camera=little1] canvas');return c&&c.getContext('2d').getImageData(0,0,c.width,c.height).data.some(x=>x);});
 for(const name of ['cajas','etiquetas','rastros'])await page.getByRole('button',{name,exact:true}).click();
 await page.waitForFunction(()=>{const c=document.querySelector('[data-camera=little1] canvas');return c&&!c.getContext('2d').getImageData(0,0,c.width,c.height).data.some(x=>x);});
 for(const name of ['cajas','etiquetas','rastros'])await page.getByRole('button',{name,exact:true}).click();
 const gallery=page.getByRole('region',{name:'Galería de vehículos'});
 await gallery.locator('img').first().waitFor({timeout:30000});
 await gallery.locator('button[title^="#"]').first().click();
 await page.waitForTimeout(500);
 await page.getByRole('button',{name:'Ampliar Little Caesars 1',exact:true}).click();
 await page.waitForFunction(()=>!!document.fullscreenElement);await page.evaluate(()=>document.exitFullscreen());
 await page.getByRole('button',{name:'acercar',exact:true}).click();await page.getByRole('button',{name:'restablecer encuadre',exact:true}).click();
 await page.screenshot({path:output+'/edge-classic-selected.png',fullPage:true});
 // Editor persists only to the fixture store; no production zones are changed.
 const beforeZones=await (await context.request.get(origin+'/edge/api/regions')).json();
 const bootstrap=await (await context.request.get(origin+'/edge/api/bootstrap')).json();
 await page.getByRole('button',{name:'Editar zonas de esta cámara',exact:true}).click();
 const dialog=page.getByRole('dialog');await dialog.waitFor();
 await dialog.getByRole('button',{name:'Nueva exclusión',exact:true}).click();
 const area=dialog.locator('[data-zone-canvas]'),rect=await area.boundingBox();
 for(const [x,y] of [[.02,.02],[.98,.02],[.98,.98],[.02,.98]])await page.mouse.click(rect.x+x*rect.width,rect.y+y*rect.height);
 assert.equal(await area.locator('circle').count(),4);
 await dialog.getByRole('button',{name:'Cerrar polígono',exact:true}).click();
 await dialog.getByLabel('Nombre de zona',{exact:true}).fill('Prueba de exclusión');
 await page.screenshot({path:output+'/edge-zones-editor.png',fullPage:true});
 await dialog.getByRole('button',{name:'Guardar zonas',exact:true}).click();
 await dialog.waitFor({state:'detached'}).catch(async error=>{console.error('EDITOR_FAILURE',await dialog.innerText());throw error;});
 await page.getByRole('status').filter({hasText:'Zonas guardadas'}).waitFor();
 const saved=await (await context.request.get(origin+'/edge/api/regions')).json();
 assert.equal(saved.revision,beforeZones.revision+1);assert.equal(saved.profiles.little1.regions.length,1);
 assert.deepEqual(saved.profiles.crowne,beforeZones.profiles.crowne);
 await page.waitForFunction(()=>document.querySelector('[data-camera=little1]')?.textContent.includes('0 en seguimiento'));
 await page.reload();await page.getByRole('button',{name:'Little Caesars 1',exact:true}).click();
 await page.getByRole('button',{name:'Editar zonas de esta cámara',exact:true}).click();
 await dialog.getByRole('button',{name:'Prueba de exclusión',exact:true}).click();
 await dialog.getByLabel('Nombre de zona',{exact:true}).fill('Edición desactualizada');
 // Another authenticated tab changes a different camera; stale save must fail.
 const conflict=await context.request.post(origin+'/edge/api/regions',{headers:{Origin:origin,'X-CSRF-Token':bootstrap.user.csrf},data:{camera:'little',revision:saved.revision,profile:saved.profiles.little}});
 assert.equal(conflict.status(),200);
 await dialog.getByRole('button',{name:'Guardar zonas',exact:true}).click();
 await dialog.getByRole('alert').filter({hasText:'otra sesión'}).waitFor();
 await dialog.getByRole('button',{name:'Cerrar sin guardar',exact:true}).click();
 await page.getByRole('button',{name:'Editar zonas de esta cámara',exact:true}).click();
 await dialog.getByRole('button',{name:'Prueba de exclusión',exact:true}).click();
 await dialog.getByRole('button',{name:'Eliminar zona',exact:true}).click();
 await dialog.getByRole('button',{name:'Guardar zonas',exact:true}).click();await dialog.waitFor({state:'detached'}).catch(async error=>{console.error('EDITOR_FAILURE',await dialog.innerText());throw error;});
 const finalZones=await (await context.request.get(origin+'/edge/api/regions')).json();
 assert.equal(finalZones.profiles.little1.regions.length,0);
 await page.setViewportSize({width:390,height:844});
 await page.getByRole('button',{name:'Editar zonas de esta cámara',exact:true}).click();
 await page.screenshot({path:output+'/edge-zones-editor-mobile.png',fullPage:true});
 assert.equal(await dialog.evaluate(d=>d.scrollWidth>d.clientWidth+1),false);
 await dialog.getByRole('button',{name:'Cerrar sin guardar',exact:true}).click();
 await page.setViewportSize({width:390,height:844});await page.screenshot({path:output+'/edge-classic-mobile.png',fullPage:true});
 assert.equal(await page.evaluate(()=>document.documentElement.scrollWidth>innerWidth),false);
 await page.getByRole('button',{name:'Nueva prueba de inferencia',exact:true}).click();
 await page.getByText('Inferencia en tiempo real',{exact:true}).waitFor({timeout:15000});
 await page.getByText('Reproducción de grabaciones · 90 s',{exact:true}).waitFor({timeout:25000});
 assert.equal(await page.getByRole('button',{name:'Nueva prueba de inferencia',exact:true}).isEnabled(),true);
 await page.getByRole('button',{name:'Salir',exact:true}).click();await page.getByRole('link',{name:'Entrar con Zitadel'}).waitFor();
 assert.equal((await context.request.get(origin+'/edge/api/bootstrap')).status(),401);
 assert.deepEqual(errors,[]);
 const result={zones:{camera:"little1",draw:true,persistAfterReload:true,otherCamerasPreserved:true,exclusionApplied:true,staleSaveRejected:true,delete:true,mobileOverflow:false,finalRevision:finalZones.revision},initial,sought,palette,mapPins:11,mapSelection:'little1',pauseDrift:0,overlaysToggle:true,gallery:true,fullscreen:true,mapZoom:true,mobileOverflow:false,liveTransition:true,logout:true,errors};
 await writeFile(output+'/edge-zones-browser.json',JSON.stringify(result,null,2)+'\n');console.log(JSON.stringify(result));
} finally {await browser.close();}
